name: Update Template Metadata
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  update_template:
    name: Updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Fetch Node Packages
        run: yarn

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn update

      - name: List changes
        run: git status

      - name: Stage new file
        run: git add .

      - name: Commit updated metadata
        run: git commit -m "Auto-Update Metadata"
